packages: []
allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false
minimumReleaseAgeExclude:
  - miniflare@4.20260714.0
  - wrangler@4.112.0
